---
name: scheduler-demo
bundle_prefix:
  - ycappuccino.storage
  - demo
  - ycappuccino.endpoints_service
  - ycappuccino.scheduler
layers:
  ycappuccino_storage_memory:
    active: true
config:
  http_server:
    active: false
